language: python

python:
  - '2.7'

env: DB_NAME='travis_ci_test' DJANGO_SETTINGS_MODULE='settings' PYTHONPATH=$HOME/build/geodesign/django-raster

before_script:
  - psql -c 'CREATE DATABASE travis_ci_test' -U postgres
  - psql -c 'CREATE EXTENSION postgis' -U postgres -d travis_ci_test

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-gdal

install: pip install psycopg2==2.5.3 django==1.6.5 celery==3.1.11 South==1.0

script: django-admin.py test raster